BOOT_SRC_DIR := boot/src
BOOT_INC_DIR := boot/include

BOOT_SOURCES := $(call find_asm_sources,$(BOOT_SRC_DIR)) $(call find_c_sources,$(BOOT_SRC_DIR))
BOOT_OBJECTS := $(call to_objects,$(BOOT_SOURCES))
