DRIVERS_SRC_DIR := drivers
DRIVERS_INC_DIR := drivers

DRIVERS_SOURCES := $(call find_asm_sources,$(DRIVERS_SRC_DIR)) $(call find_c_sources,$(DRIVERS_SRC_DIR))
DRIVERS_OBJECTS := $(call to_objects,$(DRIVERS_SOURCES))
